version: '2'
services:
    mysql-backup:
      user: "0"
      image: deitch/mysql-backup
      environment:
       - DB_DUMP_TARGET=/backup
       - DB_USER=root
       - DB_SERVER=soptorshi-mysql
       - DB_DUMP_CRON=*/5****
      volumes:
       - ./backup:/backup
